services:
  postgres:
    image: postgres:18
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      TZ: ${TIME_ZONE}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./auth-service/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    #image: gsrlabs/auth-service:latest
    build:
      context: ./auth-service
      args:
        - TIME_ZONE=${TIME_ZONE}
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8040}:8040"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password123}
      - DB_NAME=${DB_NAME:-auth_db}
      - DB_SSLMODE=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
