services:

# -------------------------
# Authentication service
# -------------------------

  # Postgres for Authentication service
  postgres:
    image: postgres:18
    container_name: auth_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-auth_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      TZ: ${TIME_ZONE}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Authentication service app
  app:
    #image: gsrlabs/auth-service:latest
    build:
      context: ./auth-service
      args:
        - TIME_ZONE=${TIME_ZONE}
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8040}:8040"
    environment:
      - APP_PORT=${AUTH_SERVICE_APP_PORT}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password123}
      - DB_NAME=${DB_NAME:-auth_db}
      - DB_SSLMODE=disable
      - FRONTEND_HOST=${FRONTEND_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

# -------------------------
# Post service
# -------------------------

  # MongoDB for Post service
  mongo:
    image: mongo:8
    container_name: post_mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"   # Доступ с хоста (для разработки)
    environment:
      MONGO_INITDB_DATABASE: post_db
    volumes:
      - mongo_data:/data/db      # Персистентное хранение
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for cache (Post Service)
  redis:
    image: redis:8
    container_name: post_redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]  # Включаем persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Post service app
  post-service:
    build:
      context: ./post-service
    container_name: post_service
    restart: unless-stopped
    ports:
      - "8050:8050"
    environment:
      # Mongo
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=post_db

      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # gRPC Auth
      - AUTH_GRPC_HOST=auth_service
      - AUTH_GRPC_PORT=50051

      - APP_PORT=8050

    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  mongo_data:
  redis_data: